Mail:
    QA: true
    QAFolder: C:\Users\Bill.Westlake\Documents\temp\email
    Smtp:
        Host: smtp.sample.com
        Port: 25
        User: user1
        Password: pass1
DB:
    ConnectionString: MongoDB
    NumberOfDeadlockRepeats: 5
    DefaultTimeout: 00:05:00






